name: Publish Package After Tagging

on:
  push:
    tags:
      - 'v*'  # This triggers on tags that follow the versioning format, like v1.0.1

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set the version from tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}

          # Remove the leading 'v' if present
          VERSION=${TAG_NAME#v}

          echo "Updating package.json version to $VERSION"
          
          # Update the version in package.json to match the tag (without 'v' prefix)
          sed -i 's/"version": "[^"]*"/"version": "'$VERSION'"/' package.json

      - name: Show updated package.json (for debugging)
        run: cat package.json

      - name: Authenticate to GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.MY_PAT }}" > ~/.npmrc

      - name: Publish to GitHub Packages
        run: npm publish
